/**
 * scorer.js — Heuristic AI-vs-human PR scoring engine
 *
 * Scoring weights:
 *   Bot author name match       +5
 *   AI keywords in title/body   +4
 *   Co-authored-by: Copilot     +3
 *   Large diff (>500 lines)     +2
 *   Suspiciously fast creation  +2
 *   Zero comments               +1
 *   Auto-PR title pattern       +1
 *   References an issue         -3
 *   Small focused change        -2
 *   Long descriptive body       -2
 *
 * Verdict thresholds:
 *   score >= 5  → "AI Slop"
 *   score <= 2  → "Likely Human"
 *   3–4         → "Needs Review"
 */

const BOT_PATTERNS = [
  /\[bot\]/i,
  /copilot/i,
  /dependabot/i,
  /renovate/i,
  /allcontributors/i,
  /github-actions/i,
  /mergify/i,
  /snyk-bot/i,
  /deepsource/i,
  /coderabbit/i,
];

const AI_KEYWORDS = [
  /\bclaude\b/i,
  /\bcopilot\b/i,
  /\bcursor\b/i,
  /ai.generated/i,
  /ai-generated/i,
  /\bautomated\b/i,
  /generated by (claude|gpt|gemini|copilot|cursor|ai)/i,
  /\bco-authored-by.*copilot/i,
  /\bco-authored-by.*bot/i,
  /this pr (was )?generated/i,
  /using (claude|gpt|gemini|copilot|cursor)/i,
  /\bgpt-?[0-9]/i,
  /\bgemini\b/i,
];

const CO_AUTHOR_AI = /co-authored-by:.*(?:copilot|claude|cursor|github-actions|bot)/i;

const AUTO_PR_TITLE = /^(feat|fix|chore|refactor|style|perf|ci|build|docs|test)[:(\/](?![^#]*#\d)/;

const ISSUE_REF = /(close[sd]?|fix(e[sd])?|resolve[sd]?)\s+#\d+|#\d+/i;

/**
 * Score a PR and return structured result
 * @param {Object} pr - GitHub PR object (may include .commits, .files)
 * @returns {{ score: number, signals: string[], verdict: string, humanScore: number }}
 */
function scorePR(pr) {
  let score = 0;
  const signals = [];

  const title = pr.title || '';
  const body = pr.body || '';
  const authorLogin = (pr.user && pr.user.login) || '';
  const commits = pr.commits_data || [];
  const files = pr.files_data || [];

  // ── Bot author ──────────────────────────────────────────────────────────
  if (BOT_PATTERNS.some(p => p.test(authorLogin))) {
    score += 5;
    signals.push(`🤖 Bot account: @${authorLogin} (+5)`);
  }

  // ── AI keywords in title or body ────────────────────────────────────────
  const combinedText = `${title}\n${body}`;
  const aiMatches = AI_KEYWORDS.filter(k => k.test(combinedText));
  if (aiMatches.length > 0) {
    score += 4;
    signals.push(`🔑 AI keyword detected in title/body (+4)`);
  }

  // ── Co-author trailer pointing to AI ───────────────────────────────────
  if (CO_AUTHOR_AI.test(body)) {
    score += 3;
    signals.push(`👥 Co-authored-by AI trailer (+3)`);
  } else if (commits.length > 0) {
    const commitMessages = commits.map(c => c.commit && c.commit.message ? c.commit.message : '').join('\n');
    if (CO_AUTHOR_AI.test(commitMessages)) {
      score += 3;
      signals.push(`👥 Co-authored-by AI trailer in commit (+3)`);
    }
  }

  // ── Large diff (>500 lines added+removed) ───────────────────────────────
  const additions = pr.additions || 0;
  const deletions = pr.deletions || 0;
  const totalChanges = additions + deletions;
  if (totalChanges > 500) {
    score += 2;
    signals.push(`📦 Large diff: ${totalChanges} lines changed (+2)`);
  }

  // ── Suspiciously fast creation ───────────────────────────────────────────
  // If PR was created within 2 minutes of the head commit's author date
  if (commits.length > 0) {
    const lastCommit = commits[commits.length - 1];
    if (lastCommit.commit && lastCommit.commit.author && lastCommit.commit.author.date) {
      const commitTime = new Date(lastCommit.commit.author.date).getTime();
      const prTime = new Date(pr.created_at).getTime();
      const diffMinutes = Math.abs(prTime - commitTime) / 60000;
      if (diffMinutes < 2) {
        score += 2;
        signals.push(`⚡ PR created within ${diffMinutes.toFixed(1)} min of last commit (+2)`);
      }
    }
  }

  // ── No discussion (0 comments) ───────────────────────────────────────────
  if (pr.comments === 0 && pr.review_comments === 0) {
    score += 1;
    signals.push(`🔇 No discussion (0 comments) (+1)`);
  }

  // ── Auto-PR title pattern (feat:/fix: without issue ref) ────────────────
  if (AUTO_PR_TITLE.test(title) && !ISSUE_REF.test(body)) {
    score += 1;
    signals.push(`🏷️ Auto-PR title pattern without issue ref (+1)`);
  }

  // ── References a specific issue (human signal) ──────────────────────────
  if (ISSUE_REF.test(body)) {
    score -= 3;
    signals.push(`🔗 References a GitHub issue (-3)`);
  }

  // ── Small focused change (< 50 lines, 1-2 files) ────────────────────────
  const changedFiles = pr.changed_files || files.length || 0;
  if (totalChanges < 50 && changedFiles <= 2) {
    score -= 2;
    signals.push(`🎯 Small focused change: ${totalChanges} lines, ${changedFiles} files (-2)`);
  }

  // ── Long descriptive body (>500 chars) ──────────────────────────────────
  if (body.length > 500) {
    score -= 2;
    signals.push(`📝 Long descriptive body: ${body.length} chars (-2)`);
  }

  // ── Verdict ──────────────────────────────────────────────────────────────
  let verdict;
  let emoji;
  if (score >= 5) {
    verdict = 'AI Slop';
    emoji = '🚨';
  } else if (score <= 2) {
    verdict = 'Likely Human';
    emoji = '✅';
  } else {
    verdict = 'Needs Review';
    emoji = '⚠️';
  }

  return {
    score,
    signals,
    verdict,
    emoji,
    prNumber: pr.number,
    title,
    author: authorLogin,
    url: pr.html_url,
    createdAt: pr.created_at,
    additions,
    deletions,
    changedFiles,
  };
}

/**
 * Sort and bucket scored results
 */
function summarizeResults(results) {
  const aiSlop = results.filter(r => r.verdict === 'AI Slop');
  const needsReview = results.filter(r => r.verdict === 'Needs Review');
  const likelyHuman = results.filter(r => r.verdict === 'Likely Human');

  const avgScore = results.length
    ? (results.reduce((s, r) => s + r.score, 0) / results.length).toFixed(1)
    : 0;

  return { aiSlop, needsReview, likelyHuman, avgScore };
}

module.exports = { scorePR, summarizeResults };
